import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';
import * as YAML from 'yaml';
import {
  FlowGramJSON,
  FlowNodeJSON,
  FlowInputValue,
  DifyDSL,
  DifyNode,
  DifyEdge,
  DifyVariable,
  DifyPromptItem,
} from './types';

/**
 * DSL 转换器:FlowGram JSON → Dify DSL
 *
 * 这是网关层的核心组件(README 标注的"核心开发点")。
 * 负责:
 *  - 将 FlowGram 的 nodes/edges 映射为 Dify DSL 的 nodes/edges
 *  - 将 LLM 节点配置(modelName/systemPrompt/prompt/temperature)转为 Dify 格式
 *  - 处理变量引用(两边均使用 {{#nodeId.variable#}} 格式,天然兼容)
 */
@Injectable()
export class DifyConverterService {
  private readonly logger = new Logger(DifyConverterService.name);

  /** 常见模型名 → Dify provider 映射 */
  private readonly MODEL_PROVIDER_MAP: Record<string, string> = {
    'gpt-3.5-turbo': 'openai',
    'gpt-4': 'openai',
    'gpt-4o': 'openai',
    'gpt-4o-mini': 'openai',
    'gpt-4-turbo': 'openai',
    'claude-3-opus': 'anthropic',
    'claude-3-sonnet': 'anthropic',
    'claude-3-haiku': 'anthropic',
    'claude-3.5-sonnet': 'anthropic',
    'deepseek-chat': 'deepseek',
    'deepseek-reasoner': 'deepseek',
    'deepseek-v4-pro': 'deepseek',
    'deepseek-v4-flash': 'deepseek',
    'gemini-pro': 'google',
    'gemini-1.5-pro': 'google',
    'gemini-1.5-flash': 'google',
    'qwen-turbo': 'tongyi',
    'qwen-plus': 'tongyi',
    'qwen-max': 'tongyi',
  };

  /**
   * 将 FlowGram JSON 转换为 Dify DSL YAML 字符串
   */
  toDifyDSL(flowgram: FlowGramJSON): DifyDSL {
    this.validateFlowGram(flowgram);

    const startNode = flowgram.nodes.find((n) => n.type === 'start');
    const endNode = flowgram.nodes.find((n) => n.type === 'end');

    if (!startNode) {
      throw new BadRequestException('工作流缺少 Start 节点');
    }

    // 转换所有节点
    const difyNodes: DifyNode[] = flowgram.nodes.map((node) =>
      this.convertNode(node, startNode),
    );

    // 转换所有边
    const difyEdges: DifyEdge[] = flowgram.edges.map((edge) =>
      this.convertEdge(edge, flowgram.nodes),
    );

    // 如果没有 End 节点,自动补充一个指向最后一个可执行节点的输出
    if (!endNode) {
      const executableNodes = flowgram.nodes.filter(
        (n) => ['llm', 'http', 'code'].includes(n.type),
      );
      if (executableNodes.length > 0) {
        const lastNode = executableNodes[executableNodes.length - 1];
        const outputKey = lastNode.type === 'llm' ? 'text' : 'result';
        const endId = 'end_auto';
        difyNodes.push(this.createEndNode(endId, lastNode.id, 1200, 0, outputKey));
        difyEdges.push(
          this.createEdge(lastNode.id, endId, lastNode.type, 'end'),
        );
      }
    }

    const dsl: DifyDSL = {
      app: {
        description: 'Generated by futureFlow gateway',
        icon: '🤖',
        icon_background: '#FFEAD5',
        mode: 'workflow',
        name: 'futureflow_workflow',
      },
      kind: 'app',
      version: '0.1.5',
      workflow: {
        features: {
          file_upload: { image: { enabled: false } },
          opening_statement: '',
          retriever_resource: { enabled: true },
          sensitive_word_avoidance: { enabled: false },
          speech_to_text: { enabled: false },
          suggested_questions: [],
          suggested_questions_after_answer: { enabled: false },
          text_to_speech: { enabled: false },
        },
        graph: {
          nodes: difyNodes,
          edges: difyEdges,
          viewport: { x: 0, y: 0, zoom: 0.7 },
        },
      },
    };

    this.logger.log(
      `DSL 转换完成: ${flowgram.nodes.length} 节点 → ${difyNodes.length} Dify节点, ${difyEdges.length} 边`,
    );
    return dsl;
  }

  /** 转换为 YAML 字符串(用于 Dify Console API 导入) */
  toDifyDSLYaml(flowgram: FlowGramJSON): string {
    const dsl = this.toDifyDSL(flowgram);
    return YAML.stringify(dsl, { indentSeq: false });
  }

  /** 校验 FlowGram JSON 基本结构 */
  private validateFlowGram(json: FlowGramJSON) {
    if (!json || !Array.isArray(json.nodes) || !Array.isArray(json.edges)) {
      throw new BadRequestException('FlowGram JSON 必须包含 nodes 和 edges 数组');
    }
    if (json.nodes.length === 0) {
      throw new BadRequestException('工作流至少需要一个节点');
    }
    const executableNodes = json.nodes.filter(
      (n) => ['llm', 'http', 'code'].includes(n.type),
    );
    if (executableNodes.length === 0) {
      throw new BadRequestException(
        '工作流至少需要一个可执行节点(llm/http/code)',
      );
    }
  }

  /** 转换单个节点 */
  private convertNode(node: FlowNodeJSON, startNode: FlowNodeJSON): DifyNode {
    const position = node.meta?.position || { x: 0, y: 0 };
    const base = {
      id: node.id,
      type: 'custom' as const,
      position,
      positionAbsolute: { ...position },
      sourcePosition: 'right' as const,
      targetPosition: 'left' as const,
      width: 244,
      height: 168,
    };

    switch (node.type) {
      case 'start':
        return { ...base, height: 168, data: this.convertStartNode(node) };
      case 'llm':
        return { ...base, height: 98, data: this.convertLLMNode(node) };
      case 'end':
        return { ...base, height: 90, data: this.convertEndNode(node) };
      case 'http':
        return { ...base, height: 120, data: this.convertHttpNode(node) };
      case 'code':
        return { ...base, height: 120, data: this.convertCodeNode(node) };
      default:
        throw new BadRequestException(
          `暂不支持的节点类型: ${node.type}(当前支持 start/llm/end/http/code)`,
        );
    }
  }

  /** 转换 Start 节点 */
  private convertStartNode(node: FlowNodeJSON): any {
    // FlowGram 的 Start 节点用 outputs.properties 定义暴露的变量
    const properties = (node.data.outputs?.properties || {}) as Record<
      string,
      any
    >;
    const variables: DifyVariable[] = Object.entries(properties).map(
      ([key, schema]) => ({
        variable: key,
        label: key,
        type: schema.type === 'number' ? 'number' : 'paragraph',
        required: true,
        max_length: schema.type === 'number' ? 48 : 50000,
        options: [],
      }),
    );

    return {
      type: 'start',
      title: node.data.title || '开始',
      desc: '',
      selected: false,
      variables,
    };
  }

  /** 转换 LLM 节点 */
  private convertLLMNode(node: FlowNodeJSON): any {
    const inputsValues = node.data.inputsValues || {};

    const modelName = this.getInputValue(inputsValues.modelName, 'gpt-3.5-turbo');
    const temperature = parseFloat(
      String(this.getInputValue(inputsValues.temperature, 0.5)),
    );
    const systemPrompt = this.getInputValue(inputsValues.systemPrompt, '');
    const userPrompt = this.getInputValue(inputsValues.prompt, '');

    const provider = this.inferProvider(String(modelName));

    // 构建 prompt_template
    // 同时将 FlowGram 变量引用 {{nodeId.var}} 转为 Dify 格式 {{#nodeId.var#}}
    const promptTemplate: DifyPromptItem[] = [];
    if (systemPrompt) {
      promptTemplate.push({
        id: uuidv4(),
        role: 'system',
        text: this.convertVariableRefs(String(systemPrompt)),
      });
    }
    promptTemplate.push({
      id: uuidv4(),
      role: 'user',
      text: this.convertVariableRefs(String(userPrompt)),
    });

    return {
      type: 'llm',
      title: node.data.title || 'LLM',
      desc: '',
      selected: false,
      model: {
        provider,
        name: String(modelName),
        mode: 'chat',
        completion_params: {
          temperature,
        },
      },
      prompt_template: promptTemplate,
      context: {
        enabled: false,
        variable_selector: [],
      },
      vision: {
        enabled: false,
      },
      variables: [],
    };
  }

  /** 转换 End 节点 */
  private convertEndNode(node: FlowNodeJSON): any {
    // FlowGram 的 end 节点 outputs 中定义了输出
    // 需要找到上游 LLM 节点的输出作为 value_selector
    const outputs =
      (node.data.outputs?.properties as Record<string, any>) || {};
    const outputList = Object.keys(outputs).map((key) => ({
      variable: key,
      // 默认引用最近的上游 LLM 节点的 text 输出
      // value_selector 将在 convertEdge 阶段被修正,这里先留空
      value_selector: [], // 稍后由 linkEndNodeOutputs 填充
    }));

    // 如果没有定义输出,默认输出 result
    if (outputList.length === 0) {
      outputList.push({
        variable: 'result',
        value_selector: [],
      });
    }

    return {
      type: 'end',
      title: node.data.title || '结束',
      desc: '',
      selected: false,
      outputs: outputList,
    };
  }

  /** 转换 HTTP 请求节点 */
  private convertHttpNode(node: FlowNodeJSON): any {
    const inputsValues = node.data.inputsValues || {};

    const method = String(
      this.getInputValue(inputsValues.method, 'get'),
    ).toLowerCase();
    const url = String(this.getInputValue(inputsValues.url, ''));
    const headers = String(this.getInputValue(inputsValues.headers, ''));
    const body = String(this.getInputValue(inputsValues.body, ''));

    return {
      type: 'http-request',
      title: node.data.title || 'HTTP 请求',
      desc: '',
      selected: false,
      method,
      url: this.convertVariableRefs(url),
      headers: this.convertVariableRefs(headers),
      params: '',
      body: this.convertVariableRefs(body),
      body_type: body ? 'raw' : 'none',
      timeout: 30,
      variables: [],
    };
  }

  /** 转换代码执行节点 */
  private convertCodeNode(node: FlowNodeJSON): any {
    const inputsValues = node.data.inputsValues || {};

    const codeLanguage = String(
      this.getInputValue(inputsValues.codeLanguage, 'python3'),
    );
    const code = String(this.getInputValue(inputsValues.code, ''));

    // 从 outputs.properties 提取输出变量定义
    const outputsProps =
      (node.data.outputs?.properties as Record<string, any>) || {};
    const outputs = Object.keys(outputsProps).map((key) => ({
      variable: key,
      type: outputsProps[key]?.type || 'string',
    }));

    if (outputs.length === 0) {
      outputs.push({ variable: 'result', type: 'string' });
    }

    return {
      type: 'code',
      title: node.data.title || '代码执行',
      desc: '',
      selected: false,
      code_language:
        codeLanguage === 'javascript' ? 'javascript' : 'python3',
      code: this.convertVariableRefs(code),
      variables: [],
      outputs,
    };
  }

  /** 转换边 */
  private convertEdge(
    edge: FlowGramJSON['edges'][0],
    nodes: FlowNodeJSON[],
  ): DifyEdge {
    const sourceNode = nodes.find((n) => n.id === edge.sourceNodeID);
    const targetNode = nodes.find((n) => n.id === edge.targetNodeID);

    return {
      id: `${edge.sourceNodeID}-source-${edge.targetNodeID}-target`,
      source: edge.sourceNodeID,
      sourceHandle: 'source',
      target: edge.targetNodeID,
      targetHandle: 'target',
      type: 'custom',
      zIndex: 0,
      data: {
        isInIteration: false,
        sourceType: sourceNode?.type || 'custom',
        targetType: targetNode?.type || 'custom',
      },
    };
  }

  /** 创建 End 节点(自动补充) */
  private createEndNode(
    id: string,
    sourceNodeId: string,
    x: number,
    y: number,
    outputKey: string = 'text',
  ): DifyNode {
    return {
      id,
      type: 'custom',
      position: { x, y },
      positionAbsolute: { x, y },
      sourcePosition: 'right',
      targetPosition: 'left',
      width: 244,
      height: 90,
      data: {
        type: 'end',
        title: '结束',
        desc: '',
        selected: false,
        outputs: [
          {
            variable: 'result',
            value_selector: [sourceNodeId, outputKey],
          },
        ],
      },
    };
  }

  /** 创建边(自动补充) */
  private createEdge(
    source: string,
    target: string,
    sourceType: string,
    targetType: string,
  ): DifyEdge {
    return {
      id: `${source}-source-${target}-target`,
      source,
      sourceHandle: 'source',
      target,
      targetHandle: 'target',
      type: 'custom',
      zIndex: 0,
      data: { isInIteration: false, sourceType, targetType },
    };
  }

  /** 从 FlowInputValue 中提取值 */
  private getInputValue(
    input: FlowInputValue | undefined,
    defaultValue: any,
  ): any {
    if (!input) return defaultValue;
    return input.content !== undefined ? input.content : defaultValue;
  }

  /** 根据模型名推断 Dify provider */
  private inferProvider(modelName: string): string {
    // 精确匹配
    if (this.MODEL_PROVIDER_MAP[modelName]) {
      return this.MODEL_PROVIDER_MAP[modelName];
    }
    // 前缀匹配
    if (modelName.startsWith('gpt')) return 'openai';
    if (modelName.startsWith('claude')) return 'anthropic';
    if (modelName.startsWith('deepseek')) return 'deepseek';
    if (modelName.startsWith('gemini')) return 'google';
    if (modelName.startsWith('qwen')) return 'tongyi';
    return 'openai'; // 默认
  }

  /**
   * 将 FlowGram 变量引用语法转为 Dify 格式
   * FlowGram: {{nodeId.variable}}  或  {{nodeId.variable.subfield}}
   * Dify:     {{#nodeId.variable#}} 或 {{#nodeId.variable.subfield#}}
   */
  private convertVariableRefs(text: string): string {
    if (!text) return text;
    // 匹配 {{xxx.yyy}} 或 {{xxx.yyy.zzz}} 格式(不包含 # 的才是 FlowGram 格式)
    return text.replace(/\{\{([^}#]+)\}\}/g, (match, inner: string) => {
      const trimmed = inner.trim();
      // 如果已经是 Dify 格式 {{#...#}} 跳过
      if (trimmed.startsWith('#')) return match;
      return `{{#${trimmed}#}}`;
    });
  }

  /**
   * 从 FlowGram JSON 中提取工作流输入变量
   * 用于调用 Dify /v1/workflows/run 时填充 inputs
   * 从 Start 节点的 outputs.properties 中提取变量名和默认值
   */
  extractInputs(flowgram: FlowGramJSON): Record<string, any> {
    const startNode = flowgram.nodes.find((n) => n.type === 'start');
    if (!startNode) return {};

    const properties = (startNode.data.outputs?.properties || {}) as Record<
      string,
      any
    >;
    const inputsValues = startNode.data.inputsValues || {};
    const inputs: Record<string, any> = {};

    for (const key of Object.keys(properties)) {
      // 优先使用 inputsValues 中的值,否则用 schema default
      const val = inputsValues[key];
      if (val && val.content !== undefined) {
        inputs[key] = val.content;
      } else if (properties[key].default !== undefined) {
        inputs[key] = properties[key].default;
      } else {
        // 根据类型给默认值
        inputs[key] = properties[key].type === 'number' ? 0 : '';
      }
    }
    return inputs;
  }

  /**
   * 预估工作流费用(元)
   * 基于节点配置粗略估算,实际费用由 Dify 返回的 token 用量决定
   */
  estimateCost(flowgram: FlowGramJSON): number {
    let cost = 0;
    for (const node of flowgram.nodes) {
      if (node.type === 'llm') {
        const modelName = String(
          this.getInputValue(
            node.data.inputsValues?.modelName,
            'gpt-3.5-turbo',
          ),
        );
        // 粗略预估:每次 LLM 调用约 1000 tokens
        const estimatedTokens = 1000;
        cost += this.estimateTokenCost(modelName, estimatedTokens);
      }
    }
    return Math.round(cost * 10000) / 10000; // 保留 4 位小数
  }

  /** 根据模型和 token 数估算费用(元) */
  private estimateTokenCost(modelName: string, tokens: number): number {
    // 简化的定价表(元/1K tokens),实际应从配置读取
    const pricing: Record<string, number> = {
      'gpt-3.5-turbo': 0.005,
      'gpt-4': 0.15,
      'gpt-4o': 0.03,
      'gpt-4o-mini': 0.001,
      'claude-3-sonnet': 0.02,
      'claude-3.5-sonnet': 0.02,
      'deepseek-chat': 0.001,
    };
    const pricePer1K = pricing[modelName] || 0.01;
    return (tokens / 1000) * pricePer1K;
  }
}
