export const FIELD_LABELS: Record<string, string> = {
  query: '用户输入',
  modelName: '模型名称',
  temperature: '生成温度',
  systemPrompt: '系统提示词',
  prompt: '用户提示词',
  result: '结果',
  input: '输入参数',
  text: '文本内容',
  url: '资源地址',
  caption: '说明文字',
  poster: '视频封面',
  mediaType: '媒体类型',
  referenceUrl: '参考素材地址',
  negativePrompt: '反向提示词',
  jobId: '媒体任务 ID',
  assetId: '媒体资产 ID',
  provider: '生成供应商',
  model: '生成模型',
  taskId: '供应商任务 ID',
  status: '生成状态',
  mimeType: '文件类型',
  byteSize: '文件大小（字节）',
  sha256: '文件校验值',
  body: '响应内容',
  headers: '响应头',
  statusCode: '状态码',
  userId: '用户标识',
};

export const getFieldLabel = (key: string) => FIELD_LABELS[key] || key;
